In [2]:
import pandas as pd
import numpy as np

In [118]:
test = pd.DataFrame({'SEDOL': ['A']*10 + ['B']*5 + ['C']*3,
                     'Date': np.array([0,1,2,3,4,6,7,8,9,10,5,6,7,8,9,0,1,3]),
                     'Data': np.ones(18)})

In [117]:
test

Data  Date SEDOL  Count
0    1.0     0     A    0.0
1    1.0     1     A    0.0
2    1.0     2     A    0.0
3    1.0     3     A    0.0
4    1.0     4     A    0.0
5    1.0     6     A    1.0
6    1.0     7     A    1.0
7    1.0     8     A    1.0
8    1.0     9     A    1.0
9    1.0    10     A    1.0
10   1.0     5     B    0.0
11   1.0     6     B    0.0
12   1.0     7     B    0.0
13   1.0     8     B    0.0
14   1.0     9     B    0.0
15   1.0     0     C    0.0
16   1.0     1     C    0.0
17   1.0     3     C    1.0

In [37]:
test2 = np.array([0,1,2,3,4,5,12,13,14,20,21])

In [59]:
np.append(0, np.cumsum(np.diff(test2)>1))

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2])

In [42]:
test3 = np.zeros(5)

In [66]:
test3.shape[0]//3*3

3

In [119]:
test['Count'] = test.groupby('SEDOL')['Date'].transform(lambda x: np.append(0, np.cumsum(np.diff(x)>1)))

In [81]:
test['Count_na'] = test.groupby('SEDOL')['Count'].transform(lambda x: pd.Series([0]*x.shape[0]))

In [113]:
def insert_na(series, time_step):
    
    output = np.zeros_like(series)
    
    length = output.shape[0]//time_step * time_step
    output[length:] = np.nan
    
    return output

In [121]:
test.groupby('Count')['Count'].transform(lambda x: insert_na(x, 3))

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
Name: Count, dtype: int32

In [126]:
insert_na(test['Count'], 4)

array([          0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0, -2147483648, -2147483648])

In [127]:
a = np.zeros_like(test['Count'])

In [128]:
length = a.shape[0]//5*5

In [129]:
a[length:] = np.nan

In [130]:
a

array([          0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
       -2147483648, -2147483648, -2147483648])

In [131]:
np.nan

nan